### ISSUE TITLE
Will CircuitNet include more EDA tasks?

### ISSUE THREAD

**Issue by PKUterran** [circuitnet/CircuitNet#12]
CircuitNet really helps us a lot in congestion prediction research. Now we are working on various EDA tasks, for example, global placement. The open-source datasets on placement are few and they are in different formats (bookshelf/lefdef) which are hard to convert. We use ISPD and DAC datasets in DREAMPlace, but it might not be enough to produce convincing results. It will be greatly appreciated if CircuitNet can include more EDA tasks like global placement.

**Comment by apri0426** [comment]
Thank you for using CircuitNet! We do plan to support more tasks in the future.
About global placement, we have released lefdef (def is dumped after placement) in the last update on Dec 29, 2022. There are 10242 def and they can be used for placement by ignoring placed cells.
