### ISSUE TITLE
真实的node不在node_attr内？

### ISSUE THREAD

**Issue by gjhhust** [circuitnet/CircuitNet#17]
instance_placement是真实node的放置位置，mapper = node_attr[0] #将node index映射为真实放置名 因此mapper长度一般大于instance_placement，按道理mapper 一定包含instance_placement，这样instance_placement才能通过mapper查询到node index，接着可以查询pin_attr找到node的pin，然后就能查询到node链接的net，但是我突然发现instance_placement有2000多个在mapper 中查询不到？如下图一个例子
![image](https://user-images.githubusercontent.com/73829930/233115380-8148649b-6e21-4b3f-aebc-4375d795fff4.png)

接着我查询了整个instance_placement
![image](https://user-images.githubusercontent.com/73829930/233116166-b46d63e7-1e05-4318-a7c5-7c2a7b2f24f4.png)
得到misscnt=2426，为什么？是意味着这些真实node没有pin？

**Comment by apri0426** [comment]
这是因为node_attr是直接从综合后的netlist提出来的，instance plaement是从place后的def提出来的，而innovus读入设计以及optDesign功能会导致cell的增减，这里会有node数量的不一致。你可以参考整个issue: circuitnet/CircuitNet#11

**Comment by gjhhust** [comment]
太感谢您了，之前看graph介绍的时候还没太理解innovus will add or delete cells的意思，现在理解了！
