### ISSUE TITLE
About align instance placement and node attributes

### ISSUE THREAD

**Issue by Doctor-James** [circuitnet/CircuitNet#18]
Hello, I would like to ask for advice：In [issues 11](https://github.com/circuitnet/CircuitNet/issues/11) I can understand “the node attribute always has more values than instance placement”, but I found that some of the cells in the instance placement are not found in the node attribute, which means they are placed but not connected to any other cells?

**Comment by apri0426** [comment]
Yes, there are some physical only cells, like filler and welltap, and they will not be connected to the other cells.
