### ISSUE TITLE
About  congestion label

### ISSUE THREAD

**Issue by Doctor-James** [circuitnet/CircuitNet#19]
I found that the label value of many areas without node in the congestion label is a very small value like 0.0612（4466-RISCY-FPU-a-1-c20-u0.8-m4-p4-f0）, but not 0. Why is this?

**Comment by apri0426** [comment]
If you are looking at the label in training set, they are resized and normalized by generating_training_set.py, and during resizing (scipy.ndimage.zoom), the 0 will be changed to a small value. 

Please look at the original features.
