### ISSUE TITLE
Expand the dataset

### ISSUE THREAD

**Issue by chenmagi** [circuitnet/CircuitNet#21]
Hi,

Is there any way to expand the dataset to include such like flip-flop cell density map, and cell pin density map?

Best,

Magi

**Comment by apri0426** [comment]
Sure, we have released codes for feature extraction on July 24th. You can refer to the function compute_cell_density/get_RUDY (the part for pin RUDY) in /feature_extraction/src/read.py to compute flip-flop cell density map/cell pin density map with the LEF/DEF we released, then modify the generate_training_set.py to add it into the input of the model. 

We can also include functions for these features in next update, but it may take some time.
