### ISSUE TITLE
python precess.py问题

### ISSUE THREAD

**Issue by zzxxxl** [circuitnet/CircuitNet#23]
我运行这个函数只得到两行输出，不知道是什么原因，我的pytorch版本是pytorch11.3+cu116，运行这个函数不会报错，但是到训练的时候会因为缺少文件报错
<img width="292" alt="image" src="https://github.com/circuitnet/CircuitNet/assets/103178086/d70006a5-0bf6-4fbd-8e45-7728efa696c5">

**Comment by apri0426** [comment]
请问后续的python generate_training_set.py和python generate_csv.py运行了吗
