### ISSUE TITLE
About File Mismatch Issues

### ISSUE THREAD

**Issue by luoxiaotian521** [circuitnet/CircuitNet#31]
1.When I run python generate_training_set.py for CN-14,there are 11 files just in feature directory,but not in label directory.
![image](https://github.com/circuitnet/CircuitNet/assets/106373354/e9e288bd-fab6-42a5-8972-62c5540bfbf6)
![image](https://github.com/circuitnet/CircuitNet/assets/106373354/ff527a86-eb84-4261-bea2-b9a0a3778b6d)
2.when i run test.py, i found the test.csv is not matched to the training_set
![image](https://github.com/circuitnet/CircuitNet/assets/106373354/3d1f2005-5922-4d46-a6f0-60ebc26b5c07)
so,how can i solve these questions

**Comment by luoxiaotian521** [comment]
![image](https://github.com/circuitnet/CircuitNet/assets/106373354/b0df9af8-e1a4-4187-a33c-077bf6bcc569)
when i see other question,i think maybe i need  this file.

**Comment by apri0426** [comment]
Just uploaded the csv for N14.

**Comment by luoxiaotian521** [comment]
OK，THANK YOU.
