### ISSUE TITLE
解压N14_timing_features_post_cts中的使用cat指令合并后的net_edges.tar.gz文件时遇到的问题

### ISSUE THREAD

**Issue by EDAZQL** [circuitnet/CircuitNet#32]
您好，我想问一下circuitnet里14nm工艺中的时序预测相关的问题，我在解压N14_timing_features_post_cts中的使用cat指令合并后的net_edges.tar.gz文件时遇到了下述问题：
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
是否是文件不完整导致的，还是说是网络问题导致的，能否提供一些解决办法。

**Comment by apri0426** [comment]
google drive上下载下来的文件，他会无视后缀，所以认为所有的net_edges.tar.gz文件是相同名字的，会把这些文件重命名，比如变成"net_edges-01.tar.gz00"。所以你在cat之前要先把他们统一重命名回net_edges.tar.gz。
保证这一点之后应该能正常解压。
现在网盘上面的文件为了处理上面的问题已经全部重命名了，不需要重复下载。
