### ISSUE TITLE
Error finding data while trying to run feature extraction

### ISSUE THREAD

**Issue by sabajhn** [circuitnet/CircuitNet#34]
I'm following this totruial [https://github.com/circuitnet/CircuitNet/blob/main/feature_extraction/README.md](url) .  

I've put DFF files in the following directory: ` feature_extraction/data/DFF` and when I ran` process_data.py` I got this error `NotADirectoryError: [Errno 20] Not a directory: './data/15/detailed_route.def.gz` .

I can't find `detailed_route.def.gz` in the dataset?

**Comment by apri0426** [comment]
I don't quite understand your problem.
`process_data.py` will try to find a file named `detailed_route.def.gz` (you can change this name in `process_data.py`) in every dir under `feature_extraction/data`, so make sure you have these files.
