### ISSUE TITLE
For the issue of mismatched files in the routing features section of N14

### ISSUE THREAD

**Issue by lichengjin10** [circuitnet/CircuitNet#36]
When I run python generate_training_set.py for CN-14,There are 10 files in the label that do not match.
![20240524132204](https://github.com/circuitnet/CircuitNet/assets/100848256/fb615caf-8c2e-469a-9fa0-7c1524a33232)

I looked at the question commented by luoxiaotian521 on April 4th, and you mentioned the CSV file for N14. I generated a name_list using the file name provided in the CVS file to run generate-training_set.py, but there is still an issue with the file not being present.

![20240524132938](https://github.com/circuitnet/CircuitNet/assets/100848256/d6bae4a3-c5fb-40d9-a682-5402c1c8b783)
so,how can i solve these questions

**Comment by freshfishcode12** [comment]
me too

**Comment by apri0426** [comment]
The issue originates from a mismatch in the number of files for each feature in N14. I have updated generate_training_set.py to avoid this issue for now, and we will update the features to match their numbers soon.

**Comment by lichengjin10** [comment]
Okay, thank you for your reply. Looking forward to your update.

**Comment by zhu-jinbo** [comment]
Hello, have you solved this problem?    
`https://github.com/circuitnet/CircuitNet/issues/36`
Why did I still encounter the same problem？
