### ISSUE TITLE
没有Innovus，使用开源的布局引擎可以特征提取吗？

### ISSUE THREAD

**Issue by SivanLaai** [circuitnet/CircuitNet#37]
feature_extraction 里面提到 需要innovus才能提取，因为某些情况没有这个条件使用innovus，可以在DREAMPlace的跑布局下去做提取吗？

**Comment by apri0426** [comment]
可以尝试用OpenROAD或者IEDA等开源工具提取，不过特征提取的代码也需要相应的修改。
