### ISSUE TITLE
关于GPDL模型架构的问题

### ISSUE THREAD

**Issue by sandytruant** [circuitnet/CircuitNet#39]
为什么https://circuitnet.github.io/tutorial/experiment_tutorial.html中画出的模型架构输出通道数是1,而代码中Decoder的输出通道数是2？

**Comment by bbooxxx** [comment]
I have the same question with Truant.

**Comment by apri0426** [comment]
架构图是从原论文中截出来的，他们用的输出通道是1。而由于他们没有开源代码，我们的代码是自行复现的，并不保证完全一样。
本质上来说，congestion的label是有horizontal和vertical 2个通道的，他们可以通过取max合成1个通道。模型通道的数量取决于怎样处理这个label，1和2都是可行的，具体我也不记得哪一种实验结果更好了，不过release代码的时候用的是2个通道的版本，跟他们的架构图确实有一点出入。
