### ISSUE TITLE
Train. py code error in net_dealy_prdiction

### ISSUE THREAD

**Issue by zhu-jinbo** [circuitnet/CircuitNet#45]
When I tried to run train.by in net_dealy_prdiction, I found an error message with an unresolved reference in test-loss_tot_otssprop. I tried for a long time but couldn't find a solution. What does it mean? Should this be test_rss_tot_net_delays?
![4128676af983f8b7dc4b0ddb574e227](https://github.com/user-attachments/assets/bba2a3b1-6794-41c5-ba7c-6004332c0b70)

**Comment by apri0426** [comment]
Yes, it should be test_rss_tot_net_delays. Thank you for your reply.
