### ISSUE TITLE
Question About Transfer Learning

### ISSUE THREAD

**Issue by zxxsong** [circuitnet/CircuitNet#47]
Hi！I‘m currently reading your paper **_(CircuitNet: An Open-Source Dataset for Machine Learning in VLSI CAD Applications With
Improved Domain-Specific Evaluation Metric and Learning Strategies)_**, and the paper mentions that a **tranfer learning framwork** from **CircuitNet** to **ISPD 2015**. But I didn't find this framwork in the code. Will you plan to share it in the future? Looking forword to your reply!😀

**Comment by apri0426** [comment]
Sure, we will release it in the next update. The implementation is quite simple, you can simply instantiate a copy of the model as the teacher model.
