### ISSUE TITLE
Visualization of congestion prediction

### ISSUE THREAD

**Issue by invincible-28** [circuitnet/CircuitNet#49]
I would like to visualize the congestion map that is predicted using the congestion prediction model as shown in Figure B.1 in the ICLR conference paper: CIRCUITNET 2.0: AN ADVANCED DATASET FOR PROMOTING MACHINE LEARNING INNOVATIONS IN REALISTIC CHIP DESIGN ENVIRONMENT. url=https://openreview.net/forum?id=nMFSUjxMIl

I went through this repository but I was not able to find any function that has been implemented to write out the predicted and ground truth congestion maps, could you please point me to that if it is available? It would be very helpful to see the hotspots/ the congested areas in the design.

The code routability_ir_drop_prediction/test.py only prints out the values of the evaluation metrics.

**Comment by apri0426** [comment]
https://github.com/circuitnet/CircuitNet/blob/icisc_2023/sample_model_training/test.py
take a look at this: line 144-156
