### ISSUE TITLE
decompress.py directory setup issues

### ISSUE THREAD

**Issue by choltz95** [circuitnet/CircuitNet#5]
Hi-- Thanks so much for working on this!

Re the decompression scripts in the data gdrive directory, I think there may be some communicability issue with the decompression scripts. For example, in `decompress_routability.py` only the `decompress_path='routability_features_decompressed'` directory is created, but none of the sub-directories are created (e.g. `routability_features_decompressed/RUDY`).

In other words, when I run `decompress_routability.py`, the RUDY files are not generated. To resolve, I think there should be a line to create the child directory. Maybe something like `os.system("mkdir -p %s" % (parent.replace('routability_features','routability_features_decompressed')))` after the first loop. I used this:

```
import os

decompress_path = '../routability_features_decompressed'
os.system("mkdir -p %s " % (decompress_path))
filelist = os.walk('../routability_features')

for parent,dirnames,filenames in filelist:
    os.system("mkdir -p %s " % (parent.replace('routability_features','routability_features_decompressed')))
    for filename in filenames:
        if os.path.splitext(filename)[1] == '.gz':
            filepath = os.path.join(parent, filename)
            os.system('gzip -dk %s' % filepath)
            os.system('tar -xf %s -C %s' % (filepath.replace('.gz',''), parent.replace('routability_features','routability_features_decompressed')))
```

**Comment by apri0426** [comment]
Hi, thank you for using our dataset!  The script in the drive should be working now, sorry for the trouble!
