### ISSUE TITLE
Problems with dataset visualization

### ISSUE THREAD

**Issue by Doctor-James** [circuitnet/CircuitNet#9]
Hi, I had some confusion when visualizing 1-RISCY-a-1-c2-u0.7-m1-p1-f0，I've visualized the file in ‘instance_placement/1-RISCY-a-1-c2-u0.7-m1-p1-f0’ and it doesn't seem to match the given feature（Macro_region，RUDY, Pin_RUDY）

See the detailed visualizing results in https://github.com/Doctor-James/CircuitNet/tree/master/images
and my visualizing code in https://github.com/Doctor-James/CircuitNet/blob/master/view_data.py    (For the sake of privacy，the absolute path is blurred）

Thanks!

**Comment by apri0426** [comment]
Hi James, thank you for using CircuitNet.

First, please use the latest version of instance placement uploaded on 11/12/2022.

Second, the mismatch mainly comes from the difference in the axis between a numpy array and an image, so you need to turn the numpy array 90 degrees counterclockwise when you do visualization.

Last, please revisit the usage of cv2.rectangle. In your case, the code should be 
```
xl = int(value[0])
yb = int(value[1])
xr = int(value[2])
yt = int(value[3])
img = cv2.rectangle(img, (xl, 400-yt), (xr, 400-yb), 255, -1)
```
